#pragma once

#include <unistd.h>
#include <dirent.h>

#include "general.h"

#include "panel.h"

#include "keyboard_manager.h"

bool stringIsPartiallyMatching(char* substring, char* string){
    while(*substring){
        if(*substring++ != *string++){
            return false;
        }
    }

    return true;
}

Buffer<char*> openFilePanelGenerateSuggestions(GapBuffer* buffer){
    // TODO(Sarmis) this is an allocation party
    // reusing buffers would've been much better
    Buffer<char*> result = {};

    char* filename = gapToString(buffer);

    String filenameString = cloneString(filename);
    String directoryString = cloneString(".");
    String fullpathString = filenameString;

    u32 lastSlash = characterLastOccurence(filenameString, '/');
    if(lastSlash){
        directoryString = subString(filenameString, 0, lastSlash);
        filenameString = subString(filenameString, lastSlash + 1, filenameString.size);
        fullpathString = directoryString + "/" + filenameString;
    }

    DIR* directory = opendir((char*)directoryString.data);
    if (directory) {
        struct dirent* directoryEntry;
        while ((directoryEntry = readdir(directory)) != NULL) {
            if(stringIsPartiallyMatching((char*)filenameString.data, directoryEntry->d_name)){
                bufferAppend<char*>(&result, directoryEntry->d_name);
            }
        }
        closedir(directory);
    }

    if(filenameString.data != fullpathString.data){
        delete[] fullpathString.data;
        delete[] filenameString.data;
    } else {
        delete[] filenameString.data;
    }
    delete[] directoryString.data;

    return result;
} 

bool openFileTick(void* data0, void* data1, void* data2){
    Panel* panel = (Panel*)data0;
    KeyboardManager* keyboardManager = (KeyboardManager*)data2;

    bool wasKeyTyped = panelDefaultTick(data0, data1, data2);
    if(wasKeyTyped){
        // TODO(Sarmis) the data generated by the dirent is not 
        // actually clean so do something about that...
        bufferClean(&panel->suggestions);
        panel->suggestions = openFilePanelGenerateSuggestions(&panel->buffer);
    }
}